"""
Training a Stereographic Transformer on a Sequence Modeling Task

This demo trains a small stereographic transformer on a synthetic task:
predicting the next token in sequences generated by a context-free grammar.

The stereographic attention mechanism replaces standard dot-product attention
with attention computed via the conformal kernel on the sphere.

Requirements: numpy only (no PyTorch dependency for portability)
"""

import numpy as np
from collections import defaultdict

# ============================================================================
# Stereographic Attention Core
# ============================================================================

def inv_stereo(y):
    """Inverse stereographic projection ℝⁿ → Sⁿ⁺¹."""
    sq = np.sum(y**2, axis=-1, keepdims=True)
    D = 1 + sq
    return np.concatenate([2*y/D, (sq-1)/D], axis=-1)

def stereo_attn_forward(Q, K, V, temperature=1.0):
    """Forward pass of stereographic attention."""
    Qs = inv_stereo(Q)
    Ks = inv_stereo(K)
    logits = Qs @ Ks.T / temperature
    logits -= logits.max(axis=-1, keepdims=True)
    w = np.exp(logits)
    w /= w.sum(axis=-1, keepdims=True)
    return w @ V, w

# ============================================================================
# Minimal Transformer Components (NumPy)
# ============================================================================

def layer_norm(x, eps=1e-5):
    """Layer normalization."""
    mean = x.mean(axis=-1, keepdims=True)
    var = x.var(axis=-1, keepdims=True)
    return (x - mean) / np.sqrt(var + eps)

def relu(x):
    return np.maximum(0, x)

def softmax(x, axis=-1):
    e = np.exp(x - x.max(axis=axis, keepdims=True))
    return e / e.sum(axis=axis, keepdims=True)

class StereoTransformerBlock:
    """A single stereographic transformer block."""

    def __init__(self, d_model, d_ff, rng):
        scale = 0.02
        # Attention projections
        self.Wq = rng.randn(d_model, d_model) * scale
        self.Wk = rng.randn(d_model, d_model) * scale
        self.Wv = rng.randn(d_model, d_model) * scale
        self.Wo = rng.randn(d_model, d_model) * scale

        # FFN
        self.W1 = rng.randn(d_model, d_ff) * scale
        self.b1 = np.zeros(d_ff)
        self.W2 = rng.randn(d_ff, d_model) * scale
        self.b2 = np.zeros(d_model)

    def forward(self, x):
        # Stereographic self-attention
        Q = x @ self.Wq
        K = x @ self.Wk
        V = x @ self.Wv
        attn_out, weights = stereo_attn_forward(Q, K, V, temperature=1.0)
        attn_out = attn_out @ self.Wo
        x = layer_norm(x + attn_out)

        # Feed-forward network
        ff_out = relu(x @ self.W1 + self.b1) @ self.W2 + self.b2
        x = layer_norm(x + ff_out)
        return x, weights


class StereoTransformer:
    """A small stereographic transformer for sequence prediction."""

    def __init__(self, vocab_size, d_model, d_ff, n_layers, max_len=128):
        self.vocab_size = vocab_size
        self.d_model = d_model
        rng = np.random.RandomState(42)

        # Embedding
        self.embed = rng.randn(vocab_size, d_model) * 0.02
        self.pos_embed = rng.randn(max_len, d_model) * 0.02

        # Transformer blocks
        self.blocks = [StereoTransformerBlock(d_model, d_ff, rng) for _ in range(n_layers)]

        # Output projection
        self.output_proj = rng.randn(d_model, vocab_size) * 0.02

    def forward(self, token_ids):
        """
        Forward pass.

        Args:
            token_ids: list of integer token IDs

        Returns:
            logits: (seq_len, vocab_size)
            all_weights: list of attention weight matrices
        """
        seq_len = len(token_ids)
        x = self.embed[token_ids] + self.pos_embed[:seq_len]

        all_weights = []
        for block in self.blocks:
            x, w = block.forward(x)
            all_weights.append(w)

        logits = x @ self.output_proj
        return logits, all_weights


# ============================================================================
# Synthetic Data: Pattern Sequences
# ============================================================================

def generate_pattern_data(n_samples, seq_len, vocab_size=16):
    """
    Generate synthetic pattern sequences for training.

    Patterns:
    1. Repetition: ABCABC...
    2. Reversal: ABCD...DCBA
    3. Arithmetic: a, a+d, a+2d, ... (mod vocab_size)
    """
    rng = np.random.RandomState(0)
    sequences = []
    labels = []

    for _ in range(n_samples):
        pattern_type = rng.randint(3)

        if pattern_type == 0:  # Repetition
            period = rng.randint(2, 5)
            base = rng.randint(0, vocab_size, size=period)
            seq = np.array([base[i % period] for i in range(seq_len + 1)])
        elif pattern_type == 1:  # Palindrome
            half = rng.randint(0, vocab_size, size=(seq_len + 1) // 2 + 1)
            seq = np.concatenate([half, half[-2::-1]])[:seq_len + 1]
        else:  # Arithmetic
            start = rng.randint(0, vocab_size)
            diff = rng.randint(1, 4)
            seq = np.array([(start + i * diff) % vocab_size for i in range(seq_len + 1)])

        sequences.append(seq[:-1])
        labels.append(seq[1:])

    return np.array(sequences), np.array(labels)


# ============================================================================
# Training Loop (Forward-only evaluation, no backprop in NumPy)
# ============================================================================

def evaluate_model(model, sequences, labels):
    """Evaluate next-token prediction accuracy."""
    correct = 0
    total = 0

    for seq, lab in zip(sequences, labels):
        logits, _ = model.forward(seq)
        preds = logits.argmax(axis=-1)
        correct += (preds == lab).sum()
        total += len(lab)

    return correct / total


def demo_training():
    """Demo the stereographic transformer architecture."""
    print("=" * 60)
    print("STEREOGRAPHIC TRANSFORMER TRAINING DEMO")
    print("=" * 60)

    vocab_size = 16
    d_model = 32
    d_ff = 64
    n_layers = 2
    seq_len = 12
    n_samples = 50

    print(f"\nArchitecture:")
    print(f"  Vocab size: {vocab_size}")
    print(f"  Model dim: {d_model}")
    print(f"  FFN dim: {d_ff}")
    print(f"  Layers: {n_layers}")
    print(f"  Attention: Stereographic (conformal kernel)")

    # Generate data
    sequences, labels = generate_pattern_data(n_samples, seq_len, vocab_size)
    print(f"\nData: {n_samples} sequences of length {seq_len}")
    print(f"  Pattern types: repetition, palindrome, arithmetic")
    print(f"  Example sequence: {sequences[0]}")
    print(f"  Example labels:   {labels[0]}")

    # Create model
    model = StereoTransformer(vocab_size, d_model, d_ff, n_layers)

    # Forward pass and analysis
    logits, attn_weights = model.forward(sequences[0])

    print(f"\nForward pass analysis:")
    print(f"  Output logits shape: {logits.shape}")
    print(f"  Attention weights shape: {attn_weights[0].shape}")

    # Analyze attention patterns
    print(f"\nAttention pattern analysis (Layer 1):")
    w = attn_weights[0]
    print(f"  Entropy per position:")
    for i in range(min(6, seq_len)):
        entropy = -np.sum(w[i] * np.log(w[i] + 1e-10))
        print(f"    Position {i}: entropy = {entropy:.3f}, "
              f"max attention = {w[i].max():.3f} at position {w[i].argmax()}")

    # Verify spherical properties
    print(f"\n  Verifying spherical properties:")
    Q = sequences[0].astype(float)
    Q_proj = model.embed[sequences[0]] @ model.blocks[0].Wq
    Q_sphere = inv_stereo(Q_proj)
    norms = np.linalg.norm(Q_sphere, axis=-1)
    print(f"    All projected queries on unit sphere: {np.allclose(norms, 1.0)}")
    print(f"    Norm range: [{norms.min():.10f}, {norms.max():.10f}]")

    # Evaluate
    accuracy = evaluate_model(model, sequences[:10], labels[:10])
    print(f"\n  Random init accuracy: {accuracy:.1%} (chance = {1/vocab_size:.1%})")

    print(f"\nNote: This demo shows the forward pass architecture.")
    print(f"Full training requires automatic differentiation (PyTorch/JAX).")
    print(f"The key insight is that all projected representations lie on")
    print(f"the unit sphere, and attention is computed via the conformal kernel.")


if __name__ == "__main__":
    demo_training()
