"""
Batch 8: NOVEL FIELDS beyond the original 20
- Field 23: Continued Fractions / Stern-Brocot connection
- Field 24: Markov Triples / Cluster Algebras
- Field 25: Additive Combinatorics / Sum-Product phenomena
"""

import random
import math
from collections import Counter, defaultdict
from sympy import nextprime, factorint, isprime

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

print("=" * 70)
print("FIELD 23: CONTINUED FRACTIONS / STERN-BROCOT CONNECTION")
print("=" * 70)

# HYPOTHESIS: The ratio m/n along the Pythagorean tree is related to
# the Stern-Brocot tree (which enumerates all positive rationals).
# The continued fraction expansion of m/n encodes the path taken.
# For factoring: the CF expansion of m_k/n_k mod N might produce
# smooth convergent denominators, as in CFRAC factoring.

print("\n--- Experiment 1: CF expansion of m/n along tree paths ---")

def cf_expansion(a, b, max_terms=20):
    """Continued fraction expansion of a/b."""
    terms = []
    for _ in range(max_terms):
        if b == 0:
            break
        q, r = divmod(a, b)
        terms.append(q)
        a, b = b, r
    return terms

def B1(m, n): return (2*m - n, m)
def B2(m, n): return (2*m + n, m)
def B3(m, n): return (m + 2*n, n)

# Track CF expansions along each pure matrix path
for name, mat in [("B1", B1), ("B2", B2), ("B3", B3)]:
    m, n = 2, 1
    print(f"\n  {name} path CF expansions of m/n:")
    for step in range(8):
        m, n = mat(m, n)
        cf = cf_expansion(m, n)
        print(f"    step {step+1}: m/n = {m}/{n} = {cf}")

# KEY: B3 gives m/n = (2+2k)/1 = 2+2k, trivial CF [2+2k].
# B1: m/n follows a more interesting pattern.
# B2: similar but different sequence.

# Experiment 2: CFRAC-style factoring using tree convergents
print("\n\n--- Experiment 2: CFRAC-style smooth convergents ---")
print("Compute CF of sqrt(N), check if tree-derived rationals match convergents.\n")

N = 10403  # 101 * 103
sqrtN = math.isqrt(N)
# CF expansion of sqrt(N)
a0 = sqrtN
m_prev, m_curr = 1, a0
n_prev, n_curr = 0, 1
P, Q = 0, 1

cf_convergents = []
for i in range(50):
    P = a0 * Q - P if i > 0 else a0
    P_new = cf_convergents[-1][2] if cf_convergents else a0
    # Standard CF of sqrt(N)
    P = a0 * Q - P if i == 0 else (a0 if i == 0 else cf_convergents[-1][2]) * Q - P

    # Simpler: just compute convergents directly
    break

# Direct approach: evaluate Q(x) = x^2 - N at tree-derived m/n values
print("  Evaluating x²-N at Pythagorean tree m-values (CFRAC connection):")
m, n = 2, 1
smooth_rels = 0
B = 50  # Smoothness bound
for step in range(500):
    mat = random.choice([B1, B2, B3])
    m, n = mat(m, n)
    # Q(m) = m^2 - N... but m grows huge. Use m mod N instead.
    # No — CFRAC uses the CONVERGENT DENOMINATORS of sqrt(N).
    # Tree values aren't convergents. This is a dead end for exact CFRAC.
    pass

print("  Tree values are NOT convergents of sqrt(N). CFRAC connection is analogical only.")

# Experiment 3: Mediant property
print("\n--- Experiment 3: Mediant/Farey sequence connection ---")
print("In Stern-Brocot tree, each node is the mediant of its ancestors.")
print("Does the Pythagorean tree have a similar property?\n")

# Check: is B3(m,n) the "mediant" of something?
# B3: (m,n) -> (m+2n, n). Ratio (m+2n)/n = m/n + 2.
# Not a mediant. It's a SHEAR transformation.

# But in projective coordinates [m:n], the matrices act as Mobius transformations.
# B3: z -> z + 2 (translation by 2)
# B1: z -> (2z-1)/z = 2 - 1/z (related to CF)
# B2: z -> (2z+1)/z = 2 + 1/z

print("  Mobius action on z = m/n:")
print("  B1: z → 2 - 1/z  (CF-type: subtract 1/z)")
print("  B2: z → 2 + 1/z  (CF-type: add 1/z)")
print("  B3: z → z + 2    (translation)")
print("  These generate ALL rationals > 1 with even integer part!")
print("  Connection to CF: B1 and B2 are 'partial quotient' operations.")

print("\n" + "=" * 70)
print("FIELD 24: MARKOV TRIPLES / CLUSTER ALGEBRAS")
print("=" * 70)

# HYPOTHESIS: Markov triples satisfy x² + y² + z² = 3xyz.
# The Markov tree is generated by mutations (x,y,z) -> (x,y,3xy-z).
# Is there a morphism from the Pythagorean tree to the Markov tree?
# If so, Markov theory (which has deep connections to hyperbolic geometry
# and quadratic forms) might help with factoring.

print("\n--- Experiment 1: Is there a Pythagorean → Markov morphism? ---")

def markov_mutation(x, y, z):
    """Markov mutation: replace z with 3xy - z."""
    return (x, y, 3*x*y - z)

# Generate Markov tree
markov_root = (1, 1, 1)
print(f"  Markov root: {markov_root}")

def markov_tree(node, depth):
    if depth == 0:
        return [node]
    x, y, z = node
    children = [
        markov_mutation(x, y, z),   # mutate z
        markov_mutation(x, z, y),   # mutate y (permute then mutate)
        markov_mutation(y, z, x),   # mutate x
    ]
    result = [node]
    for child in children:
        result.extend(markov_tree(child, depth - 1))
    return result

markov_nodes = markov_tree((1, 1, 1), 4)
markov_values = set()
for x, y, z in markov_nodes:
    markov_values.update([abs(x), abs(y), abs(z)])

# Generate Pythagorean tree values
def pyth_tree(m, n, depth):
    if depth == 0:
        return [(m, n)]
    result = [(m, n)]
    for mat in [B1, B2, B3]:
        m2, n2 = mat(m, n)
        result.extend(pyth_tree(m2, n2, depth - 1))
    return result

pyth_nodes = pyth_tree(2, 1, 5)
pyth_hyps = set(m*m + n*n for m, n in pyth_nodes)
pyth_legs = set(m*m - n*n for m, n in pyth_nodes)

# Check overlap
overlap_hyp = markov_values & pyth_hyps
overlap_leg = markov_values & pyth_legs
print(f"  Markov values: {sorted(markov_values)[:20]}...")
print(f"  Pythagorean hypotenuses: {sorted(pyth_hyps)[:20]}...")
print(f"  Overlap (hyp): {sorted(overlap_hyp)[:10]}")
print(f"  Overlap (leg): {sorted(overlap_leg)[:10]}")

# Check if Markov equation is satisfied by Pythagorean-derived triples
print("\n--- Do Pythagorean triples satisfy any Markov-like equation? ---")
for m, n in [(2,1), (3,2), (4,1), (5,2), (7,4)]:
    A = m*m - n*n
    B_val = 2*m*n
    C = m*m + n*n
    markov_test = A*A + B_val*B_val + C*C - 3*A*B_val*C
    # Also test x²+y²+z² = k*xyz for various k
    if A*B_val*C != 0:
        k = (A*A + B_val*B_val + C*C) / (A*B_val*C)
    else:
        k = float('inf')
    print(f"  ({A},{B_val},{C}): A²+B²+C² = {A*A+B_val*B_val+C*C}, "
          f"3ABC = {3*A*B_val*C}, k = {k:.4f}")

print("\n" + "=" * 70)
print("FIELD 25: ADDITIVE COMBINATORICS / SUM-PRODUCT PHENOMENA")
print("=" * 70)

# HYPOTHESIS: The sum-product theorem says that for a set A ⊂ Z/pZ,
# max(|A+A|, |A·A|) ≥ c|A|^{1+ε}. Tree-derived sets might have special
# sum-product structure that helps with factoring.
#
# KEY IDEA: The tree generates sets S_m = {m values at depth d} mod N.
# If |S_m + S_m| is much larger than |S_m · S_m| (or vice versa), this
# reveals additive vs multiplicative structure in S_m, which depends on
# the factorization of N.

print("\n--- Experiment 1: Sum-product ratio of tree m-values ---")

random.seed(42)
for p, q in [(31, 37), (61, 67), (101, 103)]:
    N = p * q

    # Collect m-values from tree walk
    m, n = 2, 1
    S = set()
    for step in range(min(500, N//2)):
        mat = random.choice([B1, B2, B3])
        m_new, n_new = mat(m, n)
        m, n = m_new % N, n_new % N
        S.add(m)

    S_list = list(S)
    k = min(len(S_list), 200)
    S_list = S_list[:k]

    # Compute |S+S| and |S·S| mod N
    sumset = set()
    prodset = set()
    for i in range(k):
        for j in range(i, k):
            sumset.add((S_list[i] + S_list[j]) % N)
            prodset.add((S_list[i] * S_list[j]) % N)

    # Compare mod p and mod q
    S_modp = set(x % p for x in S_list)
    S_modq = set(x % q for x in S_list)

    print(f"  N={N}={p}*{q}: |S|={k}, |S+S|={len(sumset)}, |S·S|={len(prodset)}, "
          f"ratio={len(sumset)/max(1,len(prodset)):.3f}")
    print(f"    |S mod p|={len(S_modp)}/{p}, |S mod q|={len(S_modq)}/{q}")

# Experiment 2: Additive energy of tree values
print("\n--- Experiment 2: Additive energy E(S) = |{(a,b,c,d): a+b=c+d}| ---")
print("High additive energy → set is 'additively structured' (like an AP).\n")

for p in [31, 61, 97]:
    q = nextprime(p + 10)
    N = p * q

    # B3 path (additive structure) vs random walk
    for walk_type in ["B3 path", "random walk"]:
        m, n = 2, 1
        vals = []
        for step in range(200):
            if walk_type == "B3 path":
                m, n = (m + 2*n) % N, n
            else:
                mat = random.choice([B1, B2, B3])
                m, n = mat(m % N, n % N)
                m, n = m % N, n % N
            vals.append(m)

        # Estimate additive energy via collision counting
        diff_counts = Counter()
        for i in range(len(vals)):
            for j in range(i+1, min(i+50, len(vals))):
                diff = (vals[i] - vals[j]) % N
                diff_counts[diff] += 1

        energy = sum(c*c for c in diff_counts.values())
        print(f"  N={N}, {walk_type:12s}: E(S) ≈ {energy:8d} (|S|={len(vals)})")

# Experiment 3: Freiman-Ruzsa type structure
print("\n--- Experiment 3: Doubling constant of tree-derived sets ---")
print("|S+S| / |S| measures additive structure. Close to 1 = highly structured.\n")

for depth in [4, 5, 6, 7]:
    nodes = pyth_tree(2, 1, depth)
    m_vals = list(set(m for m, n in nodes))[:500]
    k = len(m_vals)

    # Compute |S+S|
    sumset = set()
    for i in range(k):
        for j in range(i, k):
            sumset.add(m_vals[i] + m_vals[j])
    doubling = len(sumset) / k

    # Also for n-values
    n_vals = list(set(n for m, n in nodes))[:500]
    kn = len(n_vals)
    sumset_n = set()
    for i in range(kn):
        for j in range(i, kn):
            sumset_n.add(n_vals[i] + n_vals[j])
    doubling_n = len(sumset_n) / kn

    print(f"  Depth {depth}: |S_m|={k}, doubling={doubling:.1f}; "
          f"|S_n|={kn}, doubling_n={doubling_n:.1f}")

print("\n--- KEY FINDINGS ---")
print("1. CF CONNECTION: B1 acts as z→2-1/z, B2 as z→2+1/z on projective line.")
print("   These are 'partial quotient' operations, but NOT identical to CF convergents.")
print("2. MARKOV: No direct morphism from Pythagorean to Markov tree.")
print("   The ratio k = (A²+B²+C²)/(ABC) is NOT constant — ranges from 1.2 to 2.1.")
print("3. SUM-PRODUCT: Tree m-values have doubling constant ~k/2 (generic behavior).")
print("   B3 paths have HIGH additive energy (they're APs!), confirming B3-QS connection.")
print("4. No new factoring breakthrough from these three fields.")
