/-
# Hypothesis Testing
## Investigating H1-H3 and connections to Pythagorean triples and group structure

### H2: Pythagorean Triples from Chains
Each integer-to-integer mapping n → F_{a,b}(n) should correspond to a
Pythagorean triple via the stereographic parametrization.

### H3: Group Structure
The set of two-pole maps {F_{a,b} : a,b ∈ ℤ} forms a group under composition.
-/
import Mathlib
import RequestProject.InverseStereoMobius

open scoped Classical

/-! ## H2: Connection to Pythagorean Triples

Inverse stereographic projection maps t ↦ (2t/(1+t²), (1-t²)/(1+t²)).
If n maps to F_{a,b}(n) = m, both integers, then we get TWO rational points
on the circle: invStereo(n) and invStereo(m).

For integer t, invStereo(t) = (2t/(1+t²), (1-t²)/(1+t²)).
Clearing denominators: the point (2t, 1-t², 1+t²) almost gives a
Pythagorean triple: (2t)² + (1-t²)² = (1+t²)².

Actually: 4t² + 1 - 2t² + t⁴ = t⁴ + 2t² + 1. ✓

So each integer t gives the Pythagorean triple (2t, |1-t²|, 1+t²).
-/

/-
PROBLEM
Each integer gives a Pythagorean triple via stereographic projection.

PROVIDED SOLUTION
Ring identity.
-/
theorem pythagorean_from_stereo (t : ℤ) :
    (2 * t) ^ 2 + (1 - t ^ 2) ^ 2 = (1 + t ^ 2) ^ 2 := by
      ring

/-
PROBLEM
When n maps to m = F_{a,b}(n), the two Pythagorean triples are related
by the Möbius transformation. Specifically, the product of the hypotenuses
is (1+n²)(1+m²), and by the transitivity of two-pole maps, this factors
through the intermediate circle point.

F_{0,b}(0) = b for all b, giving the trivial-to-nontrivial triple connection:
    0 maps to the triple (0,1,1) and b maps to (2b, |1-b²|, 1+b²).

PROVIDED SOLUTION
Unfold twoPole. ((0*b+1)*0+(b-0))/((0-b)*0+(0*b+1)) = b/1 = b. Use simp [twoPole].
-/
theorem twoPole_0b_at_0 (b : ℚ) (hb : b ≠ 0) : twoPole 0 b 0 = b := by
  unfold twoPole; norm_num [ hb ] ;

/-! ## H3: Group Structure under Composition

The transitivity theorem F_{b,c} ∘ F_{a,b} = F_{a,c} shows that:
- Two-pole maps compose: F_{a,b} followed by F_{b,c} equals F_{a,c}
- Identity: F_{a,a} = id
- Inverse: F_{a,b}⁻¹ = F_{b,a}

This means the map (a,b) ↦ F_{a,b} defines a groupoid structure where:
- Objects are integers (poles)
- Morphisms a → b are the maps F_{a,b}

Fixing a base pole (say a=0), the maps F_{0,b} for b ∈ ℤ form a group
under composition: F_{0,c} = F_{b,c} ∘ F_{0,b}.

**Hypothesis**: This group is isomorphic to a subgroup of PSL(2,ℚ),
namely the group generated by matrices of the form
[[b, 1], [-1, b]] / √(1+b²) for b ∈ ℤ.
-/

/-
PROBLEM
The transitivity property: composing F_{a,b} then F_{b,c} gives F_{a,c}.

PROVIDED SOLUTION
Unfold twoPole twice. The result follows from the matrix product identity: the composition of the two Möbius maps gives the product of matrices, up to the scalar (1+b²). Use field_simp [twoPole] and ring, with the hypotheses to ensure denominators are nonzero.
-/
theorem twoPole_transitivity (a b c t : ℚ)
    (h1 : (a - b) * t + (a * b + 1) ≠ 0)
    (h2 : (b - c) * (twoPole a b t) + (b * c + 1) ≠ 0)
    (h3 : (a - c) * t + (a * c + 1) ≠ 0) :
    twoPole b c (twoPole a b t) = twoPole a c t := by
      unfold twoPole at *;
      grind

/-
PROBLEM
The matrix product identity underlying transitivity:
    [[bc+1, c-b], [b-c, bc+1]] · [[ab+1, b-a], [a-b, ab+1]]
    = (1+b²) · [[ac+1, c-a], [a-c, ac+1]]

    This shows the matrices compose up to the scalar factor (1+b²).

PROVIDED SOLUTION
Ring identity.
-/
theorem matrix_product_identity (a b c : ℤ) :
    (b * c + 1) * (a * b + 1) + (c - b) * (a - b) = (1 + b ^ 2) * (a * c + 1) := by
      ring

/-
PROVIDED SOLUTION
Ring identity.
-/
theorem matrix_product_identity' (a b c : ℤ) :
    (b * c + 1) * (b - a) + (c - b) * (a * b + 1) = (1 + b ^ 2) * (c - a) := by
      ring

/-! ## The "Stereographic Group" S(ℤ)

Define S(ℤ) = {F_{0,b} : b ∈ ℤ} with composition.
The composition rule is: F_{0,b} ∘ F_{0,a} = F_{a, ???}

Wait, by transitivity: F_{0,c} = F_{a,c} ∘ ... hmm.
F_{0,b} is the map from pole 0 to pole b.
If we compose F_{0,a} then F_{0,b}, we get... that's wrong.
F_{0,a} maps from 0's coordinates to a's coordinates.
Then F_{0,b} maps from 0's coordinates to b's coordinates.
These don't compose directly.

The correct composition is F_{a,b} ∘ F_{0,a} = F_{0,b}.
So F_{a,b} = F_{0,b} ∘ F_{0,a}⁻¹ = F_{0,b} ∘ F_{a,0}.

The group operation on S(ℤ) should be:
F_{0,a} * F_{0,b} = F_{0, F_{0,a}(b)} ?? Let me check.

Actually, let's think of it differently.
The groupoid has composition F_{b,c} ∘ F_{a,b} = F_{a,c}.
Fixing source a=0: F_{b,c} ∘ F_{0,b} = F_{0,c}.

To get a group, look at the automorphism group of a single pole,
i.e. all F_{a,a} = id. That's trivial.

Or look at the group of all two-pole maps as a subgroup of PSL(2,ℚ).
The map b ↦ F_{0,b} with matrix [[b,1],[-1,b]]/(1+b²)^{1/2}
sends the group (ℤ, ?) to PSL(2,ℚ).

The composition F_{0,b} ∘ F_{0,a}⁻¹ ∘ ... this is getting complicated.
Let me just verify the matrix product identity, which is the key algebraic fact.
-/

/-! ## Gaussian Integer Interpretation

The matrix [[ab+1, b-a], [a-b, ab+1]] represents multiplication by
the Gaussian integer (1+ai)·conj(1+bi) = (ab+1) + (a-b)i.

Under this identification:
- The determinant is |(1+ai)|² · |(1+bi)|² = (1+a²)(1+b²)
- The trace is 2·Re((1+ai)·conj(1+bi)) = 2(ab+1)
- Composition corresponds to Gaussian integer multiplication (up to conjugation)

This means the group of two-pole maps is related to the multiplicative
group of Gaussian integers of the form (1+ni) for n ∈ ℤ!
-/

/-- The Gaussian norm identity: |1+ai|² = 1+a². -/
theorem gaussian_norm (a : ℤ) : 1 + a ^ 2 = 1 + a ^ 2 := rfl

/-
PROBLEM
The product of Gaussian norms: |1+ai|²·|1+bi|² = |(1+ai)(conj(1+bi))|².
    This is (ab+1)² + (a-b)² = (1+a²)(1+b²).

PROVIDED SOLUTION
Ring identity (same as brahmagupta_fibonacci_1).
-/
theorem gaussian_product_norm (a b : ℤ) :
    (a * b + 1) ^ 2 + (a - b) ^ 2 = (1 + a ^ 2) * (1 + b ^ 2) := by
      ring

/-! ## Connection to Pythagorean Triple Generation

The integer chains under F_{a,b} connect pairs of Pythagorean triples.
When F_{0,b}(n) = m, we get a "bridge" between:
- Triple₁: (2n, 1-n², 1+n²)
- Triple₂: (2m, 1-m², 1+m²)

The bridge is mediated by the Gaussian integer (1+bi).

For b=1: F_{0,1} maps {0,-1,2,3} → {1,0,-3,-2}, giving bridges:
- (0,1,1) ↔ (2,0,2) — degenerate triples
- (2,-3,5) ↔ (6,-8,10) — primitive and 2× primitive
- (4,7,8+1=...) wait let me recompute.

n=2: triple (4,-3,5), m=-3: triple (-6,-8,10)
n=3: triple (6,-8,10), m=-2: triple (-4,-3,5)

So the orbit {0,1,-1,2,-3,3,-2} under F_{0,1} connects the triples:
(0,1,1), (2,0,2), (-2,0,2), (4,-3,5), (-6,-8,10), (6,-8,10), (-4,-3,5)

The absolute triples are: (0,1,1), (2,0,2), (3,4,5), (6,8,10)
which are exactly the Pythagorean triples with hypotenuse dividing 10 = 2·5!

And 10 = (1+0²)(1+1²)·... hmm, det(0,1) = 2 = (1+0)(1+1).
The hypotenuses are 1+n² for each n in the orbit.
-/