/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 751d888f-633f-4429-be06-c428f1308af9

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Verification of Theorem 2.1 from 'paper_ppt_monster.tex'.
We define the Berggren matrices M1 and M3 in SL(2, Z).
We define the Theta Group GammaTheta as the subgroup generated by S and T^2.
We prove that the subgroup generated by {M1, M3} is equal to GammaTheta.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the Berggren matrix M1 as an element of SL(2, Z).
-/
def M1 : Matrix.SpecialLinearGroup (Fin 2) ℤ :=
  ⟨!![2, -1; 1, 0], by
    decide +revert⟩

/-
Definition of the Berggren matrix M3 as an element of SL(2, Z).
-/
def M3 : Matrix.SpecialLinearGroup (Fin 2) ℤ :=
  ⟨!![1, 2; 0, 1], by
    decide +revert⟩

/-
Definition of the Theta Group as the subgroup generated by S and T^2.
-/
def GammaTheta : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ) :=
  Subgroup.closure {ModularGroup.S, ModularGroup.T ^ 2}

/-
Theorem 2.1: The group generated by M1 and M3 is equal to the Theta Group.
-/
theorem berggren_eq_theta : Subgroup.closure {M1, M3} = GammaTheta := by
  refine' le_antisymm _ _;
  · simp +decide [ Subgroup.closure_le, Set.insert_subset_iff ];
    refine' ⟨ Subgroup.mem_closure.mpr _, Subgroup.mem_closure.mpr _ ⟩;
    · intro K hK; have := hK ( Set.mem_insert _ _ ) ; have := hK ( Set.mem_insert_of_mem _ ( Set.mem_singleton _ ) ) ; simp_all +decide [ Set.insert_subset_iff ] ;
      convert K.mul_mem this ‹ModularGroup.S ∈ K› using 1 ; ext i j ; fin_cases i <;> fin_cases j <;> rfl;
    · intro K hK; have := hK ( Set.mem_insert_of_mem _ ( Set.mem_singleton _ ) ) ; simp_all +decide [ Set.insert_subset_iff, pow_two ] ;
      convert hK.2 using 1 ; ext i j ; fin_cases i <;> fin_cases j <;> rfl;
  · rw [ GammaTheta ];
    simp +decide [ Subgroup.closure_le, Set.insert_subset_iff ];
    constructor;
    · -- We need to show that $S \in \langle M1, M3 \rangle$.
      have hS : (ModularGroup.S : Matrix.SpecialLinearGroup (Fin 2) ℤ) = M3⁻¹ * M1 := by
        ext i j ; fin_cases i <;> fin_cases j <;> simp +decide [ M1, M3 ]
      rw [hS] at *; exact (by
      exact Subgroup.mul_mem _ ( Subgroup.inv_mem _ ( Subgroup.subset_closure ( Set.mem_insert_of_mem _ ( Set.mem_singleton _ ) ) ) ) ( Subgroup.subset_closure ( Set.mem_insert _ _ ) )); -- This completes the proof.;
    · refine' Subgroup.subset_closure _;
      right;
      ext i j ; fin_cases i <;> fin_cases j <;> rfl
