/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6b171cdb-5949-4535-81b3-e34a4b7d1d51

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Verified Theorem 6.1 from Neukirch's "Algebraic Number Theory", which states that in a Dedekind domain, for a prime ideal $\mathfrak{p}$ and $\pi \in \mathfrak{p} \setminus \mathfrak{p}^2$, every element of $\mathfrak{p}^i$ can be written as $ad+e$ with $d \in \mathcal{O}$ and $e \in \mathfrak{p}^{i+1}$. This is formalized in Mathlib as `Ideal.exists_mul_add_mem_pow_succ`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Theorem 6.1: Existence of expansion in Dedekind domains (Neukirch Prop 6.1).
-/
/--
Theorem 6.1 (Neukirch): Let $\mathcal{O}$ be a Dedekind domain, $\mathfrak{p}$ a prime ideal, $\pi \in \mathfrak{p} \setminus \mathfrak{p}^2$.
Then every element of $\mathfrak{p}^i$ can be written as $a d + e$ where $d \in \mathcal{O}$ and $e \in \mathfrak{p}^{i+1}$.
This corresponds to `Ideal.exists_mul_add_mem_pow_succ` in Mathlib.
-/
theorem theorem_6_1 {S : Type*} [CommRing S] [IsDedekindDomain S]
    {P : Ideal S} [P.IsPrime] (hP : P ≠ ⊥)
    {i : ℕ} (a c : S) (a_mem : a ∈ P ^ i)
    (a_notMem : a ∉ P ^ (i + 1)) (c_mem : c ∈ P ^ i) :
    ∃ d : S, ∃ e ∈ P ^ (i + 1), a * d + e = c := by
  exact Ideal.exists_mul_add_mem_pow_succ hP a c a_mem a_notMem c_mem
