"""
Berggren Tree Error Correction Demo

Demonstrates the connection between Pythagorean triples (generated by
the Berggren tree) and quantum error correction.

Key insight: The Lorentz form Q(a,b,c) = a² + b² - c² serves as an
error syndrome — valid codewords have Q = 0 (Pythagorean triples),
and errors produce nonzero syndromes that uniquely identify the error.
"""

import numpy as np
from typing import List, Tuple

# Berggren matrices
B1 = np.array([[1, -2, 2], [2, -1, 2], [2, -2, 3]])
B2 = np.array([[1, 2, 2], [2, 1, 2], [2, 2, 3]])
B3 = np.array([[-1, 2, 2], [-2, 1, 2], [-2, 2, 3]])

def lorentz_form(a, b, c):
    """Compute Q(a,b,c) = a² + b² - c² (the error syndrome)."""
    return a**2 + b**2 - c**2

def generate_triples(depth: int) -> List[Tuple[int, int, int, int]]:
    """Generate Pythagorean triples via the Berggren tree.
    Returns list of (a, b, c, depth)."""
    triples = []
    root = np.array([3, 4, 5])
    
    def traverse(triple, d):
        a, b, c = int(triple[0]), int(triple[1]), int(triple[2])
        if a > 0:
            triples.append((a, b, c, d))
        if d < depth:
            traverse(B1 @ triple, d + 1)
            traverse(B2 @ triple, d + 1)
            traverse(B3 @ triple, d + 1)
    
    traverse(root, 0)
    return triples

def error_detection_demo():
    """Demonstrate error detection using the Lorentz form."""
    print("=" * 60)
    print("BERGGREN TREE ERROR CORRECTION")
    print("=" * 60)
    
    # Generate triples
    triples = generate_triples(3)
    
    print(f"\nGenerated {len(triples)} Pythagorean triples (depth ≤ 3):")
    print(f"{'Triple':>20} | {'Q(a,b,c)':>10} | {'Depth':>5}")
    print("-" * 45)
    for a, b, c, d in sorted(triples, key=lambda x: x[2])[:12]:
        q = lorentz_form(a, b, c)
        print(f"({a:3d}, {b:3d}, {c:3d})" + " " * (14 - len(f"({a}, {b}, {c})")) +
              f"| {q:10d} | {d:5d}")
    
    print(f"\n→ All valid triples have Q = 0 (codespace condition)")
    
    # Error detection
    print("\n" + "-" * 60)
    print("ERROR DETECTION via Lorentz Form Syndrome")
    print("-" * 60)
    
    a, b, c = 3, 4, 5  # Base triple
    print(f"\nBase triple: ({a}, {b}, {c}), Q = {lorentz_form(a, b, c)}")
    
    print(f"\nSingle-coordinate errors on first component:")
    print(f"{'δ':>5} | {'(a+δ, b, c)':>15} | {'Q':>10} | {'2aδ+δ²':>10} | {'Match':>5}")
    print("-" * 55)
    for delta in range(-3, 4):
        if delta == 0:
            continue
        q = lorentz_form(a + delta, b, c)
        predicted = 2 * a * delta + delta**2
        match = "✓" if q == predicted else "✗"
        print(f"{delta:5d} | ({a+delta:3d}, {b:3d}, {c:3d})" + 
              " " * (8 - len(f"({a+delta}, {b}, {c})")) +
              f"| {q:10d} | {predicted:10d} | {match:>5}")
    
    print(f"\n→ Syndrome Q = 2aδ + δ² uniquely determines δ for |δ| < a = {a}")
    
    # Error correction
    print("\n" + "-" * 60)
    print("ERROR CORRECTION")
    print("-" * 60)
    
    print(f"\nGiven syndrome S = 2aδ + δ², solve for δ:")
    print(f"δ = -a + √(a² + S)  (taking the root closest to 0)")
    
    for delta in [1, -1, 2, -2]:
        syndrome = 2 * a * delta + delta**2
        # Solve: δ² + 2aδ - S = 0 → δ = -a ± √(a² + S)
        discriminant = a**2 + syndrome
        delta_recovered_pos = -a + np.sqrt(discriminant)
        delta_recovered_neg = -a - np.sqrt(discriminant)
        # Choose the one with smaller absolute value
        delta_recovered = delta_recovered_pos if abs(delta_recovered_pos) < abs(delta_recovered_neg) else delta_recovered_neg
        print(f"  δ = {delta:+d}: syndrome S = {syndrome:3d}, "
              f"recovered δ = {delta_recovered:+.0f} {'✓' if int(delta_recovered) == delta else '✗'}")

def berggren_gate_demo():
    """Demonstrate Berggren matrices as quantum gate analogues."""
    print("\n" + "=" * 60)
    print("BERGGREN MATRICES AS QUANTUM GATES")
    print("=" * 60)
    
    # Verify Lorentz form preservation
    Q = np.diag([1, 1, -1])
    
    print("\nLorentz metric Q = diag(1, 1, -1)")
    print("\nVerifying B^T Q B = Q (unitarity analogue):")
    
    for name, B in [("B₁", B1), ("B₂", B2), ("B₃", B3)]:
        preserved = B.T @ Q @ B
        is_preserved = np.allclose(preserved, Q)
        print(f"  {name}: B^T Q B = Q? {is_preserved}")
    
    # Coxeter relations
    print("\nCoxeter-like relations (Rᵢⱼ = Bᵢ · Bⱼ⁻¹ are reflections):")
    
    B1_inv = np.linalg.inv(B1).astype(int)
    B2_inv = np.linalg.inv(B2).astype(int)
    B3_inv = np.linalg.inv(B3).astype(int)
    
    R12 = B1 @ B2_inv
    R13 = B1 @ B3_inv
    R23 = B2 @ B3_inv
    
    for name, R in [("R₁₂ = B₁B₂⁻¹", R12), ("R₁₃ = B₁B₃⁻¹", R13), ("R₂₃ = B₂B₃⁻¹", R23)]:
        order = 1
        power = R.copy()
        while not np.allclose(power, np.eye(3)) and order < 20:
            power = power @ R
            order += 1
        print(f"  {name}: order = {order}" + (" (reflection!)" if order == 2 else ""))
    
    # Gate simplification
    print("\nGate simplification: Bᵢ · Bⱼ⁻¹ · Bᵢ = Bⱼ")
    for (name_i, Bi), (name_j, Bj, Bj_inv) in [
        (("B₁", B1), ("B₂", B2, B2_inv)),
        (("B₁", B1), ("B₃", B3, B3_inv)),
        (("B₂", B2), ("B₃", B3, B3_inv))
    ]:
        result = Bi @ Bj_inv @ Bi
        is_equal = np.allclose(result, Bj)
        print(f"  {name_i} · {name_j}⁻¹ · {name_i} = {name_j}? {is_equal}")

def catalan_demo():
    """Demonstrate Catalan number bracketing complexity."""
    print("\n" + "=" * 60)
    print("NON-ASSOCIATIVE BRACKETING COMPLEXITY")
    print("=" * 60)
    
    from math import comb
    
    def catalan(n):
        return comb(2*n, n) // (n + 1)
    
    print("\nCatalan numbers C(n) = number of bracketings for n+1 elements:")
    print(f"{'n':>3} | {'C(n)':>10} | {'Example bracketings':>40}")
    print("-" * 60)
    
    examples = {
        0: "a",
        1: "ab",
        2: "(ab)c, a(bc)",
        3: "((ab)c)d, (a(bc))d, (ab)(cd), a((bc)d), a(b(cd))",
        4: "14 distinct bracketings",
        5: "42 distinct bracketings"
    }
    
    for n in range(7):
        c = catalan(n)
        ex = examples.get(n, f"{c} distinct bracketings")
        print(f"{n:3d} | {c:10,} | {ex}")
    
    print("\n→ For non-associative gates, bracketing matters!")
    print("→ Circuit compilation must choose among C(n-1) options")
    print("→ C(n) ~ 4^n / (n^(3/2) √π) — exponential growth!")

if __name__ == "__main__":
    error_detection_demo()
    berggren_gate_demo()
    catalan_demo()
